"""add delivery estimate fields

Revision ID: 1e1f66dadaf3
Revises: 7a8dff687935
Create Date: 2026-08-14 12:52:28.882637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1f66dadaf3'
down_revision: Union[str, None] = '7a8dff687935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_orders', sa.Column('estimated_delivery_min', sa.Date(), nullable=True))
    op.add_column('sub_orders', sa.Column('estimated_delivery_max', sa.Date(), nullable=True))
    op.add_column('vendors', sa.Column('preparation_days', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'preparation_days')
    op.drop_column('sub_orders', 'estimated_delivery_max')
    op.drop_column('sub_orders', 'estimated_delivery_min')
    # ### end Alembic commands ###
