"""add order delivery_type

Revision ID: 28101e4e0169
Revises: 1b7a5e69d1b9
Create Date: 2026-08-10 18:02:52.244633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28101e4e0169'
down_revision: Union[str, None] = '1b7a5e69d1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column doesn't emit CREATE TYPE the way create_table does — the
    # enum type has to be created explicitly first.
    delivery_type_enum = sa.Enum('home_delivery', 'pickup_point', name='delivery_type')
    delivery_type_enum.create(op.get_bind(), checkfirst=True)

    # server_default backfills existing rows as home_delivery, then is
    # dropped so the default stays purely application-side (ORM default=),
    # matching every other column on this table.
    op.add_column(
        'orders',
        sa.Column('delivery_type', delivery_type_enum, nullable=False, server_default='home_delivery'),
    )
    op.alter_column('orders', 'delivery_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_type')
    sa.Enum(name='delivery_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
