"""add sub_order courier_id

Revision ID: 4215279f1c8f
Revises: 9b25433107ab
Create Date: 2026-08-11 09:34:59.746709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4215279f1c8f'
down_revision: Union[str, None] = '9b25433107ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_orders', sa.Column('courier_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sub_orders', 'couriers', ['courier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_orders', type_='foreignkey')
    op.drop_column('sub_orders', 'courier_id')
    # ### end Alembic commands ###
