"""add courier role and couriers table

Revision ID: 9b25433107ab
Revises: 87b30edb4c6b
Create Date: 2026-08-11 09:14:44.303827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b25433107ab'
down_revision: Union[str, None] = '87b30edb4c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alembic autogenerate doesn't detect new values on an existing Postgres
    # enum (only column/table structure) — added by hand. Safe inside this
    # transaction on PG12+ as long as the new value isn't used until a later
    # transaction (it isn't, here).
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'courier'")

    op.create_table('couriers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('moto', 'taxi', 'voiture', name='vehicle_type'), nullable=False),
    sa.Column('zone', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'suspended', name='courier_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couriers')
    # 'courier' stays in the user_role enum — Postgres has no direct "remove
    # enum value" operation (would mean rebuilding the type + every column
    # using it); not worth it for a downgrade path.
    # ### end Alembic commands ###
