"""add payments table

Revision ID: c36ebe48d345
Revises: ce26363b54f9
Create Date: 2026-08-10 04:08:31.925621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c36ebe48d345'
down_revision: Union[str, None] = 'ce26363b54f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # payment_method already exists (created by the orders table's migration) —
    # create_type=False stops this table from trying to recreate it.
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('method', postgresql.ENUM('cash_on_delivery', name='payment_method', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'cancelled', name='payment_status'), nullable=False),
    sa.Column('provider_reference', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
